embedding:
  type: "fasttext"  # or "transformer" or other embedding types
  config:
    model: 'cbow'
    dim: 300
    epoch: 10
    lr: 0.05
    wordNgrams: 2
    minn: 2
    maxn: 5
    thread: 4
  training_data_path: "data/bc_datos.xlsx"

evaluation:
  articles_file: "data/bc_datos.xlsx"
  rankings_file: "data/querys simples.txt"

mlflow:
  experiment_name: "FastText Evaluation"